(function() {var implementors = {};
implementors["failure"] = [];
implementors["quicr"] = [{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"quicr/enum.Error.html\" title=\"enum quicr::Error\">Error</a>",synthetic:false,types:["quicr::Error"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"quicr/enum.WriteError.html\" title=\"enum quicr::WriteError\">WriteError</a>",synthetic:false,types:["quicr::WriteError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"quicr/enum.ReadError.html\" title=\"enum quicr::ReadError\">ReadError</a>",synthetic:false,types:["quicr::ReadError"]},];
implementors["quicr_core"] = [{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"quicr_core/enum.EndpointError.html\" title=\"enum quicr_core::EndpointError\">EndpointError</a>",synthetic:false,types:["quicr_core::endpoint::EndpointError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"quicr_core/enum.ReadError.html\" title=\"enum quicr_core::ReadError\">ReadError</a>",synthetic:false,types:["quicr_core::endpoint::ReadError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"quicr_core/enum.WriteError.html\" title=\"enum quicr_core::WriteError\">WriteError</a>",synthetic:false,types:["quicr_core::endpoint::WriteError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"quicr_core/enum.ConnectError.html\" title=\"enum quicr_core::ConnectError\">ConnectError</a>",synthetic:false,types:["quicr_core::endpoint::ConnectError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"quicr_core/enum.ConnectionError.html\" title=\"enum quicr_core::ConnectionError\">ConnectionError</a>",synthetic:false,types:["quicr_core::endpoint::ConnectionError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
